### PR TITLE
Add doc annotations to zone api

### PR DESCRIPTION
**Pull request by jjbuchan**
Adds the basic swagger annotation to the zone api.

### CODE REVIEW

**Comment by harageth** [comment]
I lied you do need to make a pom change to tell it to also look at the ZoneApiController

https://github.com/racker/salus-telemetry-monitor-management/blob/master/pom.xml#L190

**Comment by jjbuchan** [comment]
@harageth added.

I wonder how things like https://github.com/racker/salus-telemetry-monitor-management/tree/master/src/main/java/com/rackspace/salus/monitor_management/web/model/validator will show up since it's under `model`.  Maybe that's something we'll have to filter out later.

**Comment by harageth** [comment]
> @harageth added.
> 
> I wonder how things like https://github.com/racker/salus-telemetry-monitor-management/tree/master/src/main/java/com/rackspace/salus/monitor_management/web/model/validator will show up since it's under `model`. Maybe that's something we'll have to filter out later.

It didn't show up when I just generated it. 

Having this as part of the same project does interpolate the zone endpoints in the middle of the monitor endpoints. Probably not a huge deal right now, but it would be nice to have them all grouped together at some point in the future.

**Comment by harageth** [comment]
Oh and now that both your and my PR's are merged we have two different locations for the validators. I didn't put mine in the `model` package because I didn't feel it fit in there.

**Pull request merged**
